---

all:
  vars:
    workspace: "~/code"
    #ansible_password: DevOps!23
    ansible_ssh_pass: devops
    
  children:   
      read_user_data: # group
        hosts: 
          read_user_data.default: #  default host 
            user_data_file_path: "/home/devops/code/mytest/batch_remote_runner/Pipelines/playbooks"

      remote_runner: # group
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        hosts:
          remote_runner.default # default host
  
     